// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/balancer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConnReq) Reset() {
	*x = AddConnReq{}
	mi := &file_proto_balancer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnReq) ProtoMessage() {}

func (x *AddConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balancer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnReq.ProtoReflect.Descriptor instead.
func (*AddConnReq) Descriptor() ([]byte, []int) {
	return file_proto_balancer_proto_rawDescGZIP(), []int{0}
}

func (x *AddConnReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddConnResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConnResp) Reset() {
	*x = AddConnResp{}
	mi := &file_proto_balancer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnResp) ProtoMessage() {}

func (x *AddConnResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balancer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnResp.ProtoReflect.Descriptor instead.
func (*AddConnResp) Descriptor() ([]byte, []int) {
	return file_proto_balancer_proto_rawDescGZIP(), []int{1}
}

func (x *AddConnResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DeleteConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnReq) Reset() {
	*x = DeleteConnReq{}
	mi := &file_proto_balancer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnReq) ProtoMessage() {}

func (x *DeleteConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balancer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnReq.ProtoReflect.Descriptor instead.
func (*DeleteConnReq) Descriptor() ([]byte, []int) {
	return file_proto_balancer_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteConnReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteConnResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnResp) Reset() {
	*x = DeleteConnResp{}
	mi := &file_proto_balancer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnResp) ProtoMessage() {}

func (x *DeleteConnResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balancer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnResp.ProtoReflect.Descriptor instead.
func (*DeleteConnResp) Descriptor() ([]byte, []int) {
	return file_proto_balancer_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteConnResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_proto_balancer_proto protoreflect.FileDescriptor

var file_proto_balancer_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x21, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x7f, 0x0a, 0x0c, 0x4c, 0x6f, 0x61,
	0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x79, 0x6c, 0x6f, 0x52, 0x69, 0x6c,
	0x6f, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_balancer_proto_rawDescOnce sync.Once
	file_proto_balancer_proto_rawDescData []byte
)

func file_proto_balancer_proto_rawDescGZIP() []byte {
	file_proto_balancer_proto_rawDescOnce.Do(func() {
		file_proto_balancer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_balancer_proto_rawDesc), len(file_proto_balancer_proto_rawDesc)))
	})
	return file_proto_balancer_proto_rawDescData
}

var file_proto_balancer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_balancer_proto_goTypes = []any{
	(*AddConnReq)(nil),     // 0: proto.AddConnReq
	(*AddConnResp)(nil),    // 1: proto.AddConnResp
	(*DeleteConnReq)(nil),  // 2: proto.DeleteConnReq
	(*DeleteConnResp)(nil), // 3: proto.DeleteConnResp
}
var file_proto_balancer_proto_depIdxs = []int32{
	0, // 0: proto.LoadBalancer.AddConn:input_type -> proto.AddConnReq
	2, // 1: proto.LoadBalancer.DeleteConn:input_type -> proto.DeleteConnReq
	1, // 2: proto.LoadBalancer.AddConn:output_type -> proto.AddConnResp
	3, // 3: proto.LoadBalancer.DeleteConn:output_type -> proto.DeleteConnResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_balancer_proto_init() }
func file_proto_balancer_proto_init() {
	if File_proto_balancer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_balancer_proto_rawDesc), len(file_proto_balancer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_balancer_proto_goTypes,
		DependencyIndexes: file_proto_balancer_proto_depIdxs,
		MessageInfos:      file_proto_balancer_proto_msgTypes,
	}.Build()
	File_proto_balancer_proto = out.File
	file_proto_balancer_proto_goTypes = nil
	file_proto_balancer_proto_depIdxs = nil
}
